#!/bin/sh

## Append ticket number from branch name to each commit

if [ "x" != x`cat $1 | perl -n -e'/(\[\w+-\d+\])/i && print uc($1)'` ]; then
    exit
fi

branch=$(git symbolic-ref HEAD)
if [ -n "$branch" ] && [ $branch != "master" ]; then
    line=$(head -n 1 $1)
    if [ "x" = "x$line" ]; then
        exit
    fi

    ticket=$(echo $branch | perl -n -e'/\/(\w+-\d+)/i && print uc($1)')

    if [ -n "$ticket" ]; then
        echo "[$ticket] $(cat $1)" > $1
    fi
fi

